# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: cristiandrc
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-app

provider:
  name: aws
  runtime: nodejs20.x

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: GET
          path: hello
